routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::get('/', function(){
        return view('home.index');
    })->name("home");
//Route::group(['prefix' => '{account_id}'], function () {
    Route::view('list', 'list.index');
	Route::resources([
	    'diagnosis' => 'DiagnosisController',
	    'diagnosis.criteria' => 'CriteriaController',
	    'diagnosisSteps' => 'DiagnosisStepsController',
	    'sigma' => 'SigmaController',
	    'history' => 'HistoryController',
	    'diagnosis.specifiers' => 'SpecifiersController',
	    'users' => 'UsersController',
	    // 'patient_diagnosis' => 'PatientDiagnosisController',
	]);
    Route::get('diagnosis_view', 'DiagnosisController@change_view');
	Route::post('diagnosisSteps/store', 'DiagnosisStepsController@store');
	Route::post('specifiers/store', 'SpecifiersController@store');
	// Route::put('users/update', 'UsersController@update');
	Route::get('specifiers/least_one_chosen', 'SpecifiersController@least_one_chosen');
	// Route::get('diagnosis/{id}/criteria', function ($id) {
	//     return redirect('criteria/index');
	// });
	Route::get('diagnosis/{diagnosis}/criteria/{criterion}', function ($diagnosis_id, $criterion_id) {
	    //
	});
	Route::get('diagnosis/{diagnosis}/specifiers/{specify}', function ($diagnosis_id, $specify_id) {
	    //
	});
	Route::get('patient_diagnosis/create_patient_session', 'PatientDiagnosisController@create_patient_session');
//});
// Route::get('{id}/diagnosis', function ($id) {
//     return redirect('diagnosis/show');
// })->where('id', '[0-9]+');
// Route::group(['prefix' => '{id}'], function () {
// 	Route::get('diagnosis', 'DiagnosisController@index');

// });

resources/views/home/index.blade.php
@extends( 'layouts.app')

@section('content')
<div class="art-sheet clearfix">
    <div class="art-layout-wrapper">
        <div class="art-content-layout">
            <div class="art-content-layout-row">
                <div class="art-layout-cell art-content">
                    <map name="menu_map" id="menu_map">
                    <area shape="rect" coords="337,204,564,259" href="" alt="Symptom Checker">
                    <area shape="circle" coords="268,239,20" href="/">
                    <area shape="circle" coords="292,147,20" href="/list">
                    <area shape="rect" coords="335,119,562,174" href="/list">
                    <area shape="rect" coords="333,27,560,82" href="{{route('diagnosis.index')}}">
                    <area shape="circle" coords="271,60,20" href="{{route('diagnosis.index')}}">
                    </map>
                    <img src="<?=asset('images/home-dock.png')?>" alt="" style="border-color: initial; margin-top: 2px; margin-left: 7px; border-width: 0px; width: 100%; max-width: 570px; height: auto;" usemap="#menu_map" width="570" height="293">
                </div>
            </div>
        </div>
    </div>
</div>
@endsection